### API CLIENTE - GET
GET http://localhost:8080/api/v1/usuarios

### API CLIENTE - POST
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
    "id": 0,
    "nome": "bombardiro crocodiro",
    "email": "bobardiro@crocodiro.com",
    "senha": "senhaa123abc"
    
}

### API CLIENTE - PUT
PUT  http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json

{
    "id": 0,
    "nome": "bombardiro crocodiro sauro junior",
    "email": "bobardiro@crocodiro.com",
    "senha": "senhaa123abc"
    
}

### API CLIENTE - DELETE
DELETE  http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json

